### ISSUE TITLE
my friend ,can you build jriver media center [feature request]

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/VLC_AppImage#1]

**Comment by newyorkthink** [comment]
https://www.jriver.com/download.html

and , if you can crack it, your are best hacker

**Comment by lucasmz1** [comment]
@newyorkthink Well I don't handle with cracked software due to it's copyright, maybe I can pack it for you as appimagge but I cannot share in here due to github policy.

**Comment by lucasmz1** [comment]
hope you understand that!

**Comment by newyorkthink** [comment]
> hope you understand that!

what is your telegram

**Comment by lucasmz1** [comment]
> > hope you understand that!
> 
> what is your telegram

@zainotel or simply zainotel
